### ISSUE TITLE
Magento 2.4.5 broken after installing module

### ISSUE THREAD

**Issue by konrad-konieczny** [maksuturva/magento2_svea_payments#1]
after installing module cannot perform setup:upgrade,
It seems this is caused by a plugin to the logger class:
` <type name="Magento\Framework\Logger\Monolog">
        <plugin name="svea_payment_monolog_plugin" type="Svea\SveaPayment\Plugin\Framework\Logger\MonologPlugin"/>
    </type>`
after disabling the plugin all seems to work.

Magento cloud versions: 
from composer.json
` "magento/magento-cloud-metapackage": "2.4.5",`
 
and from lock:
```
 "name": "magento/product-enterprise-edition",
            "version": "2.4.5-p5",
```

here is the error I get:
```
Cache frontend 'default' is not recognized. As well as defaultcache is not configured#0 /var/www/html/vendor/magento/framework/App/Cache/Type/FrontendPool.php(87): Magento\Framework\App\Cache\Frontend\Pool->get('default')
#1 /var/www/html/vendor/magento/framework/App/Cache/Type/Config.php(52): Magento\Framework\App\Cache\Type\FrontendPool->get('config')
#2 /var/www/html/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(65): Magento\Framework\App\Cache\Type\Config->_getFrontend()
#3 /var/www/html/vendor/magento/framework/Interception/PluginList/PluginList.php(227): Magento\Framework\Cache\Frontend\Decorator\Bare->load('global|primary|...')
#4 /var/www/html/vendor/magento/framework/Interception/PluginList/PluginList.php(190): Magento\Framework\Interception\PluginList\PluginList->_loadScopedData()
#5 /var/www/html/generated/code/Magento/Framework/Logger/Monolog/Interceptor.php(58): Magento\Framework\Interception\PluginList\PluginList->getNext('Magento\\Framewo...', 'setHandlers')
#6 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(173): Magento\Framework\Logger\Monolog\Interceptor->setHandlers(Array)
#7 /var/www/html/vendor/magento/framework/Logger/Monolog.php(32): Monolog\Logger->__construct('main', Array, Array, NULL)
#8 /var/www/html/generated/code/Magento/Framework/Logger/Monolog/Interceptor.php(14): Magento\Framework\Logger\Monolog->__construct('main', Array, Array, NULL)
#9 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\Logger\Monolog\Interceptor->__construct('main', Array, Array, NULL)
#10 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#11 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\CloudCo...')
#12 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\CloudCo...')
#13 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Psr\\Log\\LoggerI...', NULL, 'logger', 'Magento\\CloudCo...')
#14 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\CloudCo...', Array, Array)
#15 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\CloudCo...', Array, Array)
#16 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\CloudCo...', Array, Array)
#17 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\CloudCo...')
#18 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\CloudCo...')
#19 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'logger', 'Magento\\Framewo...')
#20 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Framewo...', Array, Array)
#21 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#22 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#23 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#24 /var/www/html/vendor/magento/framework/App/Cache/Frontend/Factory.php(216): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#25 /var/www/html/vendor/magento/framework/App/Cache/Frontend/Factory.php(180): Magento\Framework\App\Cache\Frontend\Factory->_applyDecorators(Object(Magento\Framework\Cache\Frontend\Decorator\TagScope))
#26 /var/www/html/vendor/magento/framework/App/Cache/Frontend/Pool.php(69): Magento\Framework\App\Cache\Frontend\Factory->create(Array)
#27 /var/www/html/vendor/magento/framework/App/Cache/Frontend/Pool.php(156): Magento\Framework\App\Cache\Frontend\Pool->_initialize()
#28 /var/www/html/vendor/magento/framework/App/Cache.php(38): Magento\Framework\App\Cache\Frontend\Pool->get('default')
#29 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\App\Cache->__construct(Object(Magento\Framework\App\Cache\Frontend\Pool), NULL)
#30 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#31 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#32 /var/www/html/vendor/magento/framework/App/Cache/Proxy.php(44): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#33 /var/www/html/vendor/magento/framework/App/Cache/Proxy.php(67): Magento\Framework\App\Cache\Proxy->_getCache()
#34 /var/www/html/vendor/magento/framework/App/ProductMetadata.php(78): Magento\Framework\App\Cache\Proxy->load('mage-version')
#35 /var/www/html/vendor/magento/framework/Console/Cli.php(99): Magento\Framework\App\ProductMetadata->getVersion()
#36 /var/www/html/bin/magento(22): Magento\Framework\Console\Cli->__construct('Magento CLI')
#37 {main}
```

**Comment by ville6000** [comment]
Thanks for flagging this @konrad-konieczny! I'm looking into it and will keep you posted.

Thanks for your patience!

**Comment by Svea-Maintainer** [comment]
Lot's of bug fixes are done after this issue was added. Now tested up to Magento 2.4.8-beta2 and PHP 8.4.

Thank you for participating and reporting the error.
